import { StyleSheet, Dimensions, Platform, StatusBar as RNStatusBar } from 'react-native';

const { width: SW } = Dimensions.get('window');
const PT = Platform.OS === 'android' ? RNStatusBar.currentHeight ?? 0 : 0;

// ── Paleta Corporativa ERP ──
export const C = {
  bg:          '#F4F1ED',
  surface:     '#FFFFFF',
  primary:     '#120B06',
  primarySoft: 'rgba(18, 11, 6, 0.05)',
  gold:        '#D4A843',
  goldSoft:    'rgba(212, 168, 67, 0.12)',
  danger:      '#D7263D',
  dangerSoft:  '#FDE8E8',
  success:     '#10B981',
  successSoft: 'rgba(16, 185, 129, 0.12)',
  textDark:    '#2D241E',
  textMuted:   '#8A7060',
  border:      '#E5E0D8',
  borderFocus: '#D1C9C0',
  overlay:     'rgba(18, 11, 6, 0.7)',
  white:       '#FFFFFF',
};

// ── Estilos Globales ──
export const s = StyleSheet.create({
  safeAreaBlue: { flex: 1, backgroundColor: C.primary, paddingTop: PT },
  scrollBase:   { flex: 1, backgroundColor: C.bg },
  cfgScreen: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24, backgroundColor: C.bg },
  cfgCard: { backgroundColor: C.surface, borderRadius: 24, padding: 32, width: '100%', maxWidth: 380, borderWidth: 1, borderColor: C.borderFocus },
  cfgLogoWrap: { marginBottom: 24, alignItems: 'center' },
  cfgLogo:     { fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif', fontSize: 32, fontWeight: '700', color: C.gold, letterSpacing: -0.5 },
  cfgLogoSub:  { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, color: C.textMuted, marginTop: 6 },
  cfgDivider:  { height: 1, backgroundColor: C.border, marginBottom: 24 },
  cfgLabel:    { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, color: C.textMuted, marginBottom: 8, textTransform: 'uppercase' },
  cfgInput: { backgroundColor: C.surface, color: C.textDark, fontSize: 18, fontWeight: '700', textAlign: 'center', letterSpacing: 1, borderRadius: 12, padding: 16, marginBottom: 20, borderWidth: 1, borderColor: C.borderFocus },
  navbar: { backgroundColor: C.primary, height: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, borderBottomWidth: 2, borderBottomColor: C.gold },
  navBrand: { fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif', fontSize: 24, fontWeight: '700', color: C.gold },
  navTitle: { position: 'absolute', left: 0, right: 0, textAlign: 'center', fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif', fontSize: 20, fontWeight: '700', color: C.surface, pointerEvents: 'none' },
  navRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  navBackBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 8, marginLeft: -4 },
  navBackText: { color: C.surface, fontWeight: '700', fontSize: 16, marginLeft: 2 },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 99, backgroundColor: C.primarySoft, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusPillText: { fontSize: 12, fontWeight: '700', color: C.surface, textTransform: 'uppercase', letterSpacing: 0.5 },
  cfgIconBtn: { padding: 10 },
  mesasSectionLabel: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, color: C.textMuted, marginBottom: 16, marginLeft: 4, textTransform: 'uppercase' },
  mesasGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  mesaCard: { width: (SW - 40) / 2, backgroundColor: C.surface, borderRadius: 12, padding: 16, borderWidth: 1, borderColor: C.border, overflow: 'hidden' },
  mesaCardOcupada: { backgroundColor: C.surface, borderColor: C.danger, borderWidth: 2 },
  mesaCardBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 4 },
  mesaCardNombre: { fontSize: 24, fontWeight: '800', textAlign: 'center', marginTop: 16, marginBottom: 16 },
  mesaCardBadge: { alignSelf: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginBottom: 12, borderWidth: 1 },
  mesaCardBadgeText: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase' },
  mesaCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12, borderTopWidth: 1, borderTopColor: C.border },
  mesaCardItems: { fontSize: 12, color: C.textMuted, fontWeight: '700' },
  mesaCardTotal: { fontSize: 14, fontWeight: '800', color: C.textMuted },
  mesaCardTotalActivo: { color: C.primary, fontWeight: '800' },
  emptyText: { color: C.textMuted, textAlign: 'center', marginTop: 40, fontSize: 14, fontWeight: '600' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.surface, borderRadius: 12, paddingHorizontal: 16, marginBottom: 20, borderWidth: 1, borderColor: C.borderFocus },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, color: C.textDark, fontSize: 16, fontWeight: '600', paddingVertical: 16 },
  searchClear: { padding: 8 },
  quickGrid: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  quickBtn: { flex: 1, borderRadius: 12, padding: 16, alignItems: 'center', backgroundColor: C.surface, borderWidth: 1, borderColor: C.border },
  quickBtnLabel: { color: C.primary, fontWeight: '800', fontSize: 14, marginBottom: 4 },
  quickBtnPrice: { color: C.textMuted, fontWeight: '700', fontSize: 13 },
  fueraCarta: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: C.bg, borderRadius: 12, padding: 16, marginBottom: 24, borderWidth: 1, borderColor: C.borderFocus, borderStyle: 'dashed' },
  fueraCartaText: { color: C.textDark, fontWeight: '700', fontSize: 14 },
  yaPedidoCard: { backgroundColor: C.surface, borderRadius: 12, padding: 16, marginBottom: 24, borderWidth: 1, borderColor: C.border },
  yaPedidoTitle: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, color: C.primary, marginLeft: 6, textTransform: 'uppercase' },
  yaPedidoRow: { paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: C.border },
  yaPedidoItem: { fontSize: 14 },
  seccionWrap: { marginBottom: 24 },
  seccionTitle: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, color: C.textMuted, textTransform: 'uppercase', paddingBottom: 8, marginBottom: 12, borderBottomWidth: 1, borderBottomColor: C.border },
  catLabel: { fontSize: 12, fontWeight: '800', color: C.primary, textTransform: 'uppercase', marginBottom: 12, marginTop: 4 },
  platosGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  platoBtn: { width: (SW - 36) / 2, backgroundColor: C.surface, borderRadius: 12, padding: 16, borderWidth: 1, borderColor: C.border },
  platoBtnBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 3 },
  platoNombre: { color: C.textDark, fontWeight: '700', fontSize: 14, lineHeight: 18, marginTop: 8, marginBottom: 8 },
  platoPrecio: { fontWeight: '800', fontSize: 15 },
  carritoSheet: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: C.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '55%', borderWidth: 1, borderColor: C.borderFocus },
  carritoHandle: { alignItems: 'center', paddingTop: 12, paddingBottom: 12 },
  carritoHandleBar: { width: 48, height: 4, backgroundColor: C.borderFocus, borderRadius: 99 },
  carritoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: C.border },
  carritoHeaderTitle: { fontSize: 14, fontWeight: '800', color: C.textDark, textTransform: 'uppercase', letterSpacing: 0.5 },
  carritoHeaderBadge: { backgroundColor: C.primary, width: 28, height: 28, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  carritoHeaderBadgeText:{ color: C.surface, fontWeight: '800', fontSize: 13 },
  carritoLista: { paddingHorizontal: 16, maxHeight: 200 },
  carritoItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: C.border },
  carritoItemRow1: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  carritoItemNombre:{ color: C.textDark, fontWeight: '700', fontSize: 15, flex: 1, lineHeight: 22 },
  carritoItemNota: { color: C.danger, fontSize: 12, marginTop: 6, fontWeight: '600' },
  carritoItemPrecio:{ color: C.textMuted, fontWeight: '800', fontSize: 15, marginLeft: 12 },
  carritoItemRow2: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: C.bg, borderWidth: 1, borderColor: C.border },
  modBtnActiva: { backgroundColor: C.primary, borderColor: C.primary },
  modBtnText: { color: C.textDark, fontWeight: '700', fontSize: 12, marginLeft: 6 },
  modBtnTextActiva: { color: C.surface },
  carritoControles: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  notaBtn: { width: 40, height: 40, borderRadius: 8, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.border },
  qtyControls: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.surface, borderRadius: 8, borderWidth: 1, borderColor: C.border },
  qtyBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  qtyNumber: { color: C.textDark, fontWeight: '800', fontSize: 16, minWidth: 28, textAlign: 'center' },
  eliminarBtn: { width: 40, height: 40, borderRadius: 8, backgroundColor: C.dangerSoft, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.dangerSoft },
  carritoFooter: { padding: 16, borderTopWidth: 1, borderTopColor: C.border, backgroundColor: C.bg },
  btnPrimary: { backgroundColor: C.primary, borderRadius: 12, padding: 16, alignItems: 'center', flexDirection: 'row', justifyContent: 'center' },
  btnPrimaryText: { color: C.surface, fontWeight: '800', fontSize: 15, textTransform: 'uppercase', letterSpacing: 0.5 },
  btnSecondary: { padding: 16, alignItems: 'center', marginTop: 4 },
  btnSecondaryText: { color: C.textMuted, fontWeight: '800', fontSize: 14, textTransform: 'uppercase', letterSpacing: 0.5 },
  modalOverlay: { flex: 1, backgroundColor: C.overlay, justifyContent: 'center', alignItems: 'center' },
  modalCard: { backgroundColor: C.surface, borderRadius: 24, padding: 24, width: '85%', borderWidth: 1, borderColor: C.borderFocus },
  modalTitle: { fontSize: 20, fontWeight: '800', color: C.textDark, marginBottom: 8 },
  modalSubtitle: { fontSize: 13, color: C.textMuted, marginBottom: 24, fontWeight: '600' },
  modalInput: { backgroundColor: C.bg, color: C.textDark, borderRadius: 12, padding: 16, fontSize: 16, fontWeight: '500', marginBottom: 24, minHeight: 100, textAlignVertical: 'top', borderWidth: 1, borderColor: C.border },
  modalInputCompact: { backgroundColor: C.bg, color: C.textDark, borderRadius: 12, padding: 16, fontSize: 16, fontWeight: '500', marginBottom: 12, borderWidth: 1, borderColor: C.border },
  fabBtn: { position: 'absolute', bottom: 24, right: 24, backgroundColor: C.primary, width: 64, height: 64, borderRadius: 32, justifyContent: 'center', alignItems: 'center', elevation: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 4 },
  fabBadge: { position: 'absolute', top: -4, right: -4, backgroundColor: C.danger, width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: C.surface },
  fabBadgeText: { color: C.surface, fontWeight: '800', fontSize: 13 },
  badgeComanda: { position: 'absolute', top: -8, right: -8, backgroundColor: C.success, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, borderWidth: 2, borderColor: C.surface, elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.2, shadowRadius: 2, zIndex: 10 },
  badgeComandaText: { color: C.surface, fontWeight: '800', fontSize: 10, textTransform: 'uppercase' },
});